/**
 * -----------------------------------------------------------------------
 *     Copyright (C) 2010 LM Ericsson Limited.  All rights reserved.
 * -----------------------------------------------------------------------
 */
package com.ericsson.eniq.events.server.resources.gsm;

/**
 * Constants for the GSM Data Connection Feature.
 * 
 * @author ejoegaf
 * 
 * @since Dec 2011
 */
public final class GSMApplicationConstants {

    public static final String GSM_DATA_CONNECTION_SUBSCRIBER_DATA_VOLUME_RANKING_ANALYSIS = "GSM_DATA_CONNECTION_SUBSCRIBER_DATA_VOLUME_RANKING_ANALYSIS";

    public static final String GSM_DATACONNECTION_ACCESSAREA_DATAVOLUME_RANKING = "GSM_DATACONNECTION_ACCESSAREA_DATAVOLUME_RANKING";

    public static final String GSM_DATA_CONNECTION_ACCESS_AREA_DATA_VOLUME_RANKING_ANALYSIS = "GSM_DATA_CONNECTION_ACCESS_AREA_DATA_VOLUME_RANKING_ANALYSIS";

    public static final String GSM_DATA_CONNECTION_CONTROLLER_DATA_VOLUME_RANKING_ANALYSIS = "GSM_DATA_CONNECTION_CONTROLLER_DATA_VOLUME_RANKING_ANALYSIS";

    public static final String GSM_DATA_CONNECTION_SUBSCRIBER_CAUSE_CODE_LIST_ANALYSIS = "GSM_DATA_CONNECTION_SUBSCRIBER_CAUSE_CODE_LIST_ANALYSIS";

    public static final String GSM_DATA_CONNECTION_SUBSCRIBER_CAUSE_CODE_ANALYSIS = "GSM_DATA_CONNECTION_SUBSCRIBER_CAUSE_CODE_ANALYSIS";

    public static final String GSM_DATA_CONNECTION_SUBSCRIBER_SUB_CAUSE_CODE_ANALYSIS = "GSM_DATA_CONNECTION_SUBSCRIBER_SUB_CAUSE_CODE_ANALYSIS";

    public static final String GSM_DATA_CONNECTION_SUBSCRIBER_SUCCESS_CAUSE_CODE_ANALYSIS = "GSM_DATA_CONNECTION_SUBSCRIBER_SUCCESS_CAUSE_CODE_ANALYSIS";

    public static final String DATA_CONNECTION_CAUSE_CODE_ANALYSIS = "DATA_CONNECTION_CAUSE_CODE_ANALYSIS";

    public static final String GSM_DATA_CONNECTION_SUBSCRIBER_DATA_VOLUME_ANALYSIS = "GSM_DATA_CONNECTION_SUBSCRIBER_DATA_VOLUME_ANALYSIS";

    public static final String GSM_DATA_CONNECTION_SUBSCRIBER_SUB_CAUSE_CODE_DETAILED_EVENT_ANALYSIS = "GSM_DATA_CONNECTION_SUBSCRIBER_SUB_CAUSE_CODE_DETAILED_EVENT_ANALYSIS";

    public static final String DATA_CONNECTION_RANKING_ANALYSIS = "DATA_CONNECTION_RANKING_ANALYSIS";

    public static final String DATA_CONNECTION_DATAVOLUME_ANALYSIS = "DATA_CONNECTION_DATAVOLUME_ANALYSIS";

    public static final String DATA_CONNECTION_SUCCESS_CAUSE_CODE_ID_LABEL = "succ";

    public static final String DATA_CONNECTION_SUCCESS_CAUSE_CODES_REQUIRED = "isSuccessCauseCodeRequired";

    public static final String DATA_CONNECTION_ERROR_CAUSE_CODES_REQUIRED = "isErrorCauseCodeRequired";

    public static final String CAUSE_CODE_LIST_DELIMITER = ",";

    public static final String CONTROLLER_FAILURE = "CONTROLLER_FAILURE";

    public static final String IMSI_FAILURE = "IMSI_FAILURE";

    public static final String SUBSCRIBER_DATAVOL = "SUBSCRIBER_DATAVOL";

    public static final String ACCESS_AREA_DATAVOL = "ACCESS_AREA_DATAVOL";

    public static final String CONTROLLER_DATAVOL = "CONTROLLER_DATAVOL";

    public static final String GSM_PRE_AGG_TABLE_KEY = "ALL";

    public static final int FIRST_INDEX = 0;

    public static final String CC_LIST_IMSI = "CC_LIST_IMSI";

    public static final String IMSI_SCC = "IMSI_SCC";

    public static final String IMSI_CC = "IMSI_CC";

    public static final String CAUSE_CODE_PIE_CHART_IMSI = "CAUSE_CODE_PIE_CHART_IMSI";

    public static final String SUB_CAUSE_CODE_PIE_CHART_IMSI = "SUB_CAUSE_CODE_PIE_CHART_IMSI";

    public static final String SUCCESS_CAUSE_CODE_PIE_CHART_IMSI = "SUCCESS_CAUSE_CODE_PIE_CHART_IMSI";

    public static final String IMSI_FAILURE_DETAILED_CAUSECODE = "IMSI_FAILURE_DETAILED_CAUSECODE";

    public static final String URGENCY_CONDITION = "URGENCY_CONDITION";

    public static final String CAUSE_GROUP = "CAUSE_GROUP";

    public static final String EXTENDED_CAUSE = "EXTENDED_CAUSE";

    public static final String GSM_CALL_FAILURE_SUB_CAUSE_CODE_SUMMARY = "GSM_CALL_FAILURE_SUB_CAUSE_CODE_SUMMARY";

    public static final String GSM_CALL_FAILURE_BSC_GROUP_EVENT_ANALYSIS_SERVICE = "GSM_CALL_FAILURE_BSC_GROUP_EVENT_ANALYSIS_SERVICE";

    public static final String GSM_DATA_CONN_IMSI_FAILURE_DETAILED_CAUSE_CODE_ANALYSIS_SERVICE = "GSM_DATA_CONN_IMSI_FAILURE_DETAILED_CAUSE_CODE_ANALYSIS_SERVICE";

    public static final String GSM_CALL_FAILURE_IMSI_EVENT_ANALYSIS_SUMMARY = "GSM_CALL_FAILURE_IMSI_EVENT_ANALYSIS_SUMMARY";

    public static final String GSM_CALL_FAILURE_MSISDN_EVENT_ANALYSIS_SUMMARY = "GSM_CALL_FAILURE_MSISDN_EVENT_ANALYSIS_SUMMARY";

    public static final String GSM_ACCESS_CALL_FAILURE_EVENT_SUMMARY_WITHIN_ACCESS_AREA_GROUP = "GSM_ACCESS_CALL_FAILURE_EVENT_SUMMARY_WITHIN_ACCESS_AREA_GROUP";

    public static final String GSM_CALL_FAILURE_TERMINAL_EVENT_ANALYSIS_SUMMARY = "GSM_CALL_FAILURE_TERMINAL_EVENT_ANALYSIS_SUMMARY";

    public static final String GSM_CALL_FAILURE_COUNTRY_ROAMING_ANALYSIS_SUMMARY = "GSM_CALL_FAILURE_COUNTRY_ROAMING_ANALYSIS_SUMMARY";

    public static final String EXTENDED_CAUSE_VALUE = "EXTENDED_CAUSE_VALUE";

    public static final String ACCESS_AREA_DISTRIBUTION = "ACCESS_AREA_DISTRIBUTION";

    public static final String GSM_ACCESS_AREA_DISTRIBUTION_CALL_FAILURE_EVENT_SUMMARY = "GSM_ACCESS_AREA_DISTRIBUTION_CALL_FAILURE_EVENT_SUMMARY";

    public static final String GSM_ACCESS_AREA_DISTRIBUTION_CALL_FAILURE_CC_SUMMARY = "GSM_ACCESS_AREA_DISTRIBUTION_CALL_FAILURE_CC_SUMMARY";

    public static final String GSM_CALL_FAILURE_TERMINAL_CAUSE_CODE_ANALYSIS = "GSM_CALL_FAILURE_TERMINAL_CAUSE_CODE_ANALYSIS";

    public static final String GSM_CALL_FAILURE_TERMINAL_SUB_CAUSE_CODE_ANALYSIS = "GSM_CALL_FAILURE_TERMINAL_SUB_CAUSE_CODE_ANALYSIS";

    public static final String MODEL = "MODEL";

    public static final String TAC_LOWER_CASE = "tac";

    public static final String ROAMING_PARAM = "ROAMING";

}
